---
- hosts: all
  become_user: root
  vars:
    username: vagrant           # update Vagrantfile if you change this
    packer_path: ~{{ username }}/packer
  tasks:
    - name: Install Docker
      shell: curl -SsL https://get.docker.com/ | sh
      become: yes

    - name: Add user to docker group
      user: name={{ username }} groups=docker append=yes state=present
      become: yes

    # Ansible 2.2+
    # - name: Enable Docker service
    #   systemd: name=docker enabled=yes state=started
    #   become: yes

    - name: Create Packer directory
      file: dest={{ packer_path }} state=directory

    - name: Download Packer
      unarchive: src=https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip copy=no dest={{ packer_path }}

    - name: Add Packer to PATH
      lineinfile: "dest=~{{ username }}/.bashrc insertafter=EOF line='export PATH=$PATH:~/packer' state=present"